# Generated by Django 4.2.6 on 2023-10-07 20:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('sobrenome', models.CharField(max_length=100, verbose_name='Sobrenome')),
                ('email', models.EmailField(max_length=150, unique=True, verbose_name='Email')),
                ('data_nascimento', models.DateField(blank=True, null=True, verbose_name='Data Nascimento')),
            ],
        ),
        migrations.CreateModel(
            name='Carro',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=40, verbose_name='Nome')),
                ('marca', models.CharField(blank=True, max_length=10, null=True, verbose_name='Marca')),
                ('modelo', models.CharField(max_length=40, verbose_name='Modelo')),
                ('preco', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Preco')),
                ('estoque', models.IntegerField(blank=True, null=True, verbose_name='Qtd no Estoque')),
                ('imagem', models.ImageField(upload_to='core', verbose_name='IMG')),
                ('tempo_post', models.DateTimeField(auto_now_add=True)),
                ('tags', models.SlugField()),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios_produto', to='carapi.user')),
            ],
        ),
    ]
