# Generated by Django 4.2.6 on 2023-10-08 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carapi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carro',
            name='estoque',
        ),
        migrations.AddField(
            model_name='carro',
            name='kilometro',
            field=models.IntegerField(blank=True, null=True, verbose_name='Kilometro'),
        ),
    ]
