# Generated by Django 4.2.6 on 2023-10-08 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carapi', '0002_remove_carro_estoque_carro_kilometro'),
    ]

    operations = [
        migrations.AddField(
            model_name='carro',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
